### ISSUE TITLE
Login (and thus GetParameters) not consistent with specs

### ISSUE THREAD

**Issue by markusbuschhoff** [bobhelander/VoicemeeterRemote#1]
Hi. Thanks for your nice work. 

The VB-Audio specs (https://download.vb-audio.com/Download_CABLE/VoicemeeterRemoteAPI.pdf) claim, that after Login "IsParametersDirty()" must be called, as it has some important side effects. Without that call, all calls to GetParameters() may yield random results - and they actually do. Your RemoteWrapper.IsParametersDirty() is internal, so there's not even a work around when using your library.

I suggest three fixes (sorry, I dont want to make a pull req on this, as they're one-liners):

~~(1) In Remote.cs / Login() (around line 202) :~~ 

                case LoginResponse.AlreadyLoggedIn:
                // Edit: Don't!   RemoteWrapper.IsParametersDirty();     // <--- this here
                return true;

**Edit:** Rather let the application call IsParametersDirty(). See my comment.

(2)  expose   int RemoteWrapper.IsParameterDirty()

**Edit:** This MUST be called by the application to yield valid results with  GetParameters

~~(3) I could imagine to put IsParameterDirty() calls into all GetParameter...() calls, before the actual GetParameter-Wrapper-Code is called. I do not know if this is necessary or has unwanted side effects, have to try. But I have the feeling, VB only updates data for a client if IsParameterDirty() was called before.~~

**Edit:** See my comments below.

**Comment by markusbuschhoff** [comment]
Number 2: Of course it should rather have an implementation as Remote.IsParameterDirty(), but you know what I mean.

**Comment by markusbuschhoff** [comment]
A bit more of experimentation shows that IsParametersDirty() must be called before calls to GetParameters, but GetParameters only yields correct results when IsParametersDirty() == true.

This will be inresponsive

    while(1) {
          float m = VoiceMeeter.Remote.GetParameter("Strip[0].Mute");
          // .. do something with m
     }

This will sometimes (rarely) deliver wrong results (runs into the asserition with muted strip 0):

    while(1) {
         VoiceMeeter.Remote.IsParametersDirty();   // exposed in my version
         float m = VoiceMeeter.Remote.GetParameter("Strip[0].Mute");
         Debug.Assert(m == 1);    // though having strip 0 muted in the experiment, this assertion fails
     }

This always works correctly:

    while(1) 
    {
         if ( VoiceMeeter.Remote.IsParametersDirty() )
         {
              float m = VoiceMeeter.Remote.GetParameter("Strip[0].Mute");
              Debug.Assert(m == 1);    // ok, never fails assertion with strip 0 muted
         }
     }

However, this DOES NOT work and prohibits to put IsParametersDirty() right into the GetParameters functions:

    while(1) 
    {
         if ( VoiceMeeter.Remote.IsParametersDirty() )
         {
              float m = VoiceMeeter.Remote.GetParameter("Strip[0].Mute");
              Debug.Assert(m == 1);    // ok, never fails assertion with strip 0 muted
         }

         if ( VoiceMeeter.Remote.IsParametersDirty() )   // is ALWAYS false
         {
              float m = VoiceMeeter.Remote.GetParameter("Strip[1].Mute");       // Strip 1 this time
              Debug.Assert(m == 1);    // never gets executed  
         }
     }

The second call to VoiceMeeter.Remote.IsParametersDirty() always returns false. Only correct version is this (requiring to expose VoiceMeeter.Remote.IsParametersDirty() to the application);

    while(1) 
    {
         if ( VoiceMeeter.Remote.IsParametersDirty() )
         {
              float m = VoiceMeeter.Remote.GetParameter("Strip[0].Mute");
              Debug.Assert(m == 1);    // ok, never fails assertion with strip 0 muted

              m = VoiceMeeter.Remote.GetParameter("Strip[1].Mute");       // Strip 1 this time
              Debug.Assert(m == 1);    // ok, never fails assertion with strip 1muted
         }
     }

**Comment by bobhelander** [comment]
I did run into this in testing.  I am unsure how the voicemeter author wanted this method to be used.  

I will expose the IsParametersDirty() method through the Remote object.  

This unittest I have does finally work with the insight you have provided.

```

        [TestMethod]
        //[Ignore]
        public async Task TestMute()
        {
            using (var _ = await VoiceMeeter.Remote.Initialize(Voicemeeter.RunVoicemeeterParam.VoicemeeterPotato).ConfigureAwait(false))
            {
                var parameter = "Strip[0].Mute";

                if (VoiceMeeter.Remote.IsParametersDirty() != 0)
                {
                    // Get the current setting
                    var oldMuteSetting = VoiceMeeter.Remote.GetParameter(parameter);

                    // Mute it
                    VoiceMeeter.Remote.SetParameter(parameter, 1);
                    await Task.Delay(1000);

                    if (VoiceMeeter.Remote.IsParametersDirty() != 0)
                    {
                        // Get the test value
                        var mute = VoiceMeeter.Remote.GetParameter(parameter);

                        // Set it back
                        VoiceMeeter.Remote.SetParameter(parameter, oldMuteSetting);
                        await Task.Delay(1000);

                        Assert.AreEqual(mute, 1);
                    }
                }
            }
        }

```

There has to be a better way of getting these values without checking that method every time.

Thank you for the help!
Bob

**Comment by bobhelander** [comment]
Added a class Parameters.  This is an IObservable<> that will notify the subscription when a change is detected.  GetParameter() should always be correct while this is running.
