### ISSUE TITLE
isparameterdirty(?) memory leak

### ISSUE THREAD

**Issue by desatur8** [bobhelander/VoicemeeterRemote#3]
Hi Bob, first of all thanks for the work on this, 

Been playing around a bit with the wrapper (got it via nuget packet manager and using on VB.net), it works perfectly!

i have run in a bit of a problem, I wrote a small 5 liner, to connect to VM, and sync changes to the app from VM (currently for testing, only doing A1,A2 and mute for strip[0])

one thing i have noticed, the my app runs about 20mb in mem, every time i refresh (aka, calls isparameterdirty, and then query the a1, a2, mute status, the app's memory usage goes up by about 2mb

I then synced up the gain for strip 1, and noticed it more, so when my app checks isparameterdirty, and the result is 0, memory stays the same, but as soon as the result is 1, mem goes up.

So much so, that setting a timer, to check isparameterdirty , check every second, and then call a refreshUI function when dirty. Then moving the gain up and down, the apps mem usage goes up to 2gig in a matter of seconds.

Is it the parameterdirty variable growing? did i miss a way to flush it?

**Comment by bobhelander** [comment]
I am testing this on Voicemeeter Potato version 3.0.1.4
My test is running the unit test TestParmetersSubscribe() with a 60 second timeout.  Over several runs I have not seen any memory increase while changing various settings.

I have seen a memory exception while accessing VoiceMeeter's dll and calling the IsParametersDirty().  I was never able to figure out the root cause of this problem.  It was related to the .Net interop attached to the VM remote's dll.  There could be some leak here if it is happening a lot.
```
        public static int IsParametersDirty()
        {
            try
            {
                return RemoteWrapper.IsParametersDirty();
            }
            catch(Exception ex)
            {
                // TODO: Figure out the Memory Exception when calling the API
                ;
            }
            return 0;
        }
```

Post your code and I would be happy to look over it to see if it is tripping something I have not accounted for.

Bob

**Comment by desatur8** [comment]
Thanks for taking the time to reply

I am doing this in VB.net, if that makes a difference

firstly, on from load, i have the following code

```
 Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        VoiceMeeter.Remote.Initialize(VoiceMeeter.RunVoicemeeterParam.VoicemeeterPotato)
        VoiceMeeter.Remote.Login(VoiceMeeter.RunVoicemeeterParam.VoicemeeterPotato)
        Label1.Text = VoiceMeeter.Remote.GetTextParameter("strip[0].label")
        RefreshLayout()
 End Sub
```

and then, in the RefreshLayout, I have : 

``` 
Private Sub RefreshLayout()

        If VoiceMeeter.Remote.IsParametersDirty() = 1 Then
            If VoiceMeeter.Remote.GetParameter("strip[0].A1") = 0 Then
                pnlA1.BackgroundImage = Image.FromFile("Z:\tempIcons\a1-off.png")
            ElseIf VoiceMeeter.Remote.GetParameter("strip[0].A1") = 1 Then
                pnlA1.BackgroundImage = Image.FromFile("Z:\tempIcons\a1-on.png")
            End If

            If VoiceMeeter.Remote.GetParameter("strip[0].A2") = 0 Then
                pnlA2.BackgroundImage = Image.FromFile("Z:\tempIcons\a2-off.png")
            ElseIf VoiceMeeter.Remote.GetParameter("strip[0].A2") = 1 Then
                pnlA2.BackgroundImage = Image.FromFile("Z:\tempIcons\a2-on.png")
            End If

            If VoiceMeeter.Remote.GetParameter("strip[0].B1") = 0 Then
                pnlB1.BackgroundImage = Image.FromFile("Z:\tempIcons\b1-off.png")
            ElseIf VoiceMeeter.Remote.GetParameter("strip[0].B1") = 1 Then
                pnlB1.BackgroundImage = Image.FromFile("Z:\tempIcons\b1-on.png")
            End If

            If VoiceMeeter.Remote.GetParameter("strip[0].B2") = 0 Then
                pnlB2.BackgroundImage = Image.FromFile("Z:\tempIcons\b2-off.png")
            ElseIf VoiceMeeter.Remote.GetParameter("strip[0].B2") = 1 Then
                pnlB2.BackgroundImage = Image.FromFile("Z:\tempIcons\b2-on.png")
            End If

            Label2.Text = VoiceMeeter.Remote.GetParameter("strip[0].gain")

            MessageBox.Show(VoiceMeeter.Remote.IsParametersDirty.ToString())
        End If
    End Sub
```

this is still very early in testing, so excuse the code!
    
from what i can see, mem usage goes up with 2mb, each time refreshLayout is called, but only when the isDirty if is run

**Comment by bobhelander** [comment]
I am wondering if the memory is coming from the "Image.FromFile" call.  If you comment out the BackgroundImage assignments, do you still see the same behavior?

```
If VoiceMeeter.Remote.GetParameter("strip[0].A1") = 0 Then
    //pnlA1.BackgroundImage = Image.FromFile("Z:\tempIcons\a1-off.png")
ElseIf VoiceMeeter.Remote.GetParameter("strip[0].A1") = 1 Then
    //pnlA1.BackgroundImage = Image.FromFile("Z:\tempIcons\a1-on.png")
End If
```

**Comment by desatur8** [comment]
Is there a way to close the issue with a facepalm? 

lol, after reading your comment, I was like .... wait a min! how did I miss that!? Just tested it, no more massive mem increases! the code obv kept loading the image from file OVER AND OVER again! 

Thanks for the help man, appreciate it
